### ISSUE TITLE
add-on has stopped working

### ISSUE THREAD

**Issue by JGEscot** [ryanburns23/paper-weather#12]
It now says "Error Getting Weather" when calling the component. Event the JS Fiddle demo throws this error https://jsfiddle.net/SlashBunny/9tnL9kj5/

**Comment by ryanburns23** [comment]
Yahoo deprecated their APIs which caused this component to stop error out. 

If you still need a solution for free weather I created a similar component that calls openweathermap APIs and is written in lit-html. 
https://github.com/ryanburns23/lit-weather

I haven’t had much time to publish docs around it but the code should be self explanatory.
