### ISSUE TITLE
'Error getting weather' happening frequently

### ISSUE THREAD

**Issue by mrsideshowjack** [ryanburns23/paper-weather#6]
[screenshot](http://puu.sh/vGiEM/b4d8259959.png) from webcomponents.org overview page.

Happening on my app as well as on the demo.

On some instances, when looking at my devtools network page, I don't see any request being made; the 'loading spinner' continues to spin, until 'Error getting weather' appears.

Other times I see the request happen, but the response from yahoo is `results: null` [screenshot](http://puu.sh/vGiRQ/1fe7281253.png)

Additionally the error image seems to be  missing.

**Comment by ryanburns23** [comment]
@mrsideshowjack  Are you still seeing issues? I haven't been able to recreate or see issues in my live apps using this. You probably just caught it when the [YQN](https://developer.yahoo.com/yql/) was down or slow. Also, there are rate limits: `Per IP limits: /v1/public/*: 2,000 calls per hour; /v1/yql/*: 20,000 calls per hour`

If you checkout the code, It just makes an [iron-ajax request to yahoo weather based on the location](https://github.com/ryanburns23/paper-weather/blob/master/paper-weather.html#L332) entered. It is set to auto, so requests are made automatically if there is a location. The loading is managed by iron-ajax as well

It looks like the error icon does 404 like you said. I'll fix this when I find time
